Controllers/AdminController.cs
using E_Book_Store.Services;
using E_Book_Store.ViewModels.Admin;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_Book_Store.Controllers;

[Authorize(Roles = nameof(Roles.Admin))]
public class AdminController : Controller
{
    private readonly UserManager<IdentityUser> UserManager;
    private readonly IEBooksService EbooksService;

    public AdminController(UserManager<IdentityUser> userManager, IEBooksService eBookService)
    {
        UserManager = userManager;
        EbooksService = eBookService;
    }

    public IActionResult Index()
    {
        return View(new AdminIndexViewModel(UserManager.Users.ToList(), EbooksService.GetEbookCount()));
    }

    public async Task<IActionResult> Delete(string Id)
    {
        await UserManager.DeleteAsync((await UserManager.FindByIdAsync(Id))!);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/EBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Book_Store.Models;
using E_Book_Store.Services;
using E_Book_Store.ViewModels.EBooks;
using FluentValidation;
using FormHelper;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace E_Book_Store.Controllers;

[Authorize]
public class EBooksController : Controller
{
    private readonly IEBooksService EBookService;
    private readonly IEBooksContentService EBookContentService;
    private readonly IValidator<EBook> EBookValidator;
    private readonly IMapper Mapper;
    private readonly UserManager<IdentityUser> UserManager;

    public EBooksController(IEBooksService eBookService, IEBooksContentService ebookContentService, IValidator<EBook> eBookValidator, IMapper mapper, UserManager<IdentityUser> userManager)
    {
        EBookService = eBookService;
        EBookContentService = ebookContentService;
        EBookValidator = eBookValidator;
        Mapper = mapper;
        UserManager = userManager;
    }

    // GET: EBooks
    //public IActionResult Index() => View(Mapper.Map<EBooksIndexViewModel>(EBookService.GetByBought(UserManager.GetUserId(User)!, false)));
    public IActionResult Index()
    {
        if (User.IsInRole(nameof(Roles.EBookEditor)))
        {
            return View(new EBooksIndexViewModel() { EBooks = EBookService.GetAll().ToList().Select(ebook => new EBooksIndexItemViewModel() { Id = ebook.Id, Author = ebook.Author, Price = ebook.Price, Title = ebook.Title, Bought = EBookService.IsBought(ebook.Id, UserManager.GetUserId(User)!) }).ToList() });
        }
        else
        {
            return View(Mapper.Map<EBooksIndexViewModel>(EBookService.GetByBought(UserManager.GetUserId(User)!, false)));
        }
    }

    // GET: EBooks/Buy/5
    public IActionResult Buy(string id)
    {
        EBookService.Buy(id, UserManager.GetUserId(User));
        return RedirectToAction(nameof(Index));
    }

    // GET: EBooks/Create
    [Authorize(Roles = nameof(Roles.EBookEditor))]
    public IActionResult Create() => View();

    // POST: EBooks/Create
    [HttpPost]
    [FormValidator]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = nameof(Roles.EBookEditor))]
    public IActionResult Create(EBooksCreateViewModel model)
    {
        EBook eBook = Mapper.Map<EBook>(model);
        var validationResult = EBookValidator.Validate(eBook);
        if (validationResult.IsValid)
        {
            EBookService.Create(eBook);
            if (!string.IsNullOrEmpty(model.Content)) EBookContentService.SetContent(eBook, model.Content);
            return RedirectToAction(nameof(Index));
        }
        return FormResult.CreateErrorResult(validationResult.Errors[0].ErrorMessage);
    }

    // GET: EBooks/Edit/5
    [Authorize(Roles = nameof(Roles.EBookEditor))]
    public IActionResult Edit(string id)
    {
        var eBook = EBookService.GetById(id);
        return eBook != null ? View(Mapper.Map<EBooksEditViewModel>(eBook)) : NotFound();
    }

    // POST: EBooks/Edit/5
    [HttpPost]
    [FormValidator]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = nameof(Roles.EBookEditor))]
    public IActionResult Edit(EBooksEditViewModel model)
    {
        EBook eBook = Mapper.Map<EBook>(model);

        var validationResult = EBookValidator.Validate(eBook);
        if (validationResult.IsValid)
        {
            EBookService.Update(eBook);
            if (!string.IsNullOrEmpty(model.Content)) EBookContentService.SetContent(eBook, model.Content);
            return RedirectToAction(nameof(Index));
        }
        return FormResult.CreateErrorResult(validationResult.Errors[0].ErrorMessage);
    }

    // GET: EBooks/Delete/5
    [Authorize(Roles = nameof(Roles.EBookEditor))]
    public IActionResult Delete(string id)
    {
        var eBook = EBookService.GetById(id);
        return eBook != null ? View(Mapper.Map<EBooksDeleteViewModel>(eBook)) : NotFound();
    }

    // POST: EBooks/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = nameof(Roles.EBookEditor))]
    public IActionResult DeleteConfirmed(EBooksDeleteViewModel model)
    {
        EBookContentService.DeleteContent(EBookService.GetById(model.Id)!);
        EBookService.Delete(model.Id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/MyEBooksController.cs
using E_Book_Store.Services;
using E_Book_Store.ViewModels.MyEBooks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_Book_Store.Controllers;

[Authorize]
public class MyEBooksController : Controller
{
    private readonly IEBooksService EBookService;
    private readonly IEBooksContentService EBooksContentService;
    private readonly UserManager<IdentityUser> UserManager;

    public MyEBooksController(IEBooksService eBookService, IEBooksContentService ebookContentService, UserManager<IdentityUser> userManager)
    {
        EBooksContentService = ebookContentService;
        EBookService = eBookService;
        UserManager = userManager;
    }

    public IActionResult Index()
    {
        return View(EBookService.GetByBought(UserManager.GetUserId(User)!, true).Select(ebook => new MyEBooksItemViewModel() { Author = ebook.Author, Title = ebook.Title, Id = ebook.Id}));
    }

    public IActionResult Read(string id)
    {
        var eBook = EBookService.GetById(id);
        if (eBook == null) return NotFound();

        if (EBookService.IsBought(id, UserManager.GetUserId(User)!))
        {
            return View(new MyEBooksReadViewModel() { Author = eBook.Author, Content = EBooksContentService.GetContent(eBook), Title = eBook.Title });
        }
        else
        {
            return Forbid();
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    bool isAdmin = User.IsInRole(nameof(Roles.Admin));
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Book_Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Book_Store.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow" style="background-color: hsl(261deg 40% 88%);">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="justify-content: space-between; margin: 5px; padding: 0px 200px;">
                        <li class="nav-item">
                            <a class="button" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="button" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="button" asp-area="" asp-controller="EBooks" asp-action="Index">EBooks</a>
                        </li>
                        <li class="nav-item">
                            <a class="button" asp-area="" asp-controller="MyEBooks" asp-action="Index">My EBooks</a>
                        </li>
                        @if(isAdmin)
                        {
                            <li class="nav-item">
                                <a class="button" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                            </li>
                        }
                        @{await Html.RenderPartialAsync("_LoginPartial");}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: hsl(261deg 40% 88%);">
        <div class="container" style="text-align: center;">
            EBooks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>